dev-memento/ANDROID-MEMENTO

app/src/main/java/org/memento/ui/theme/Color.kt

- closed #8 
- Gradient color 3종 추가
메~~

[Add/#8] Gradient 색상 3종 추가

---

app/src/main/java/org/memento/presentation/component/MementoBottomSheet.kt
app/src/main/java/org/memento/presentation/component/MementoChipSelector.kt
app/src/main/java/org/memento/presentation/component/MementoTagBottomSheetItem.kt
app/src/main/java/org/memento/presentation/component/MementoTextBottomSheetItem.kt
app/src/main/java/org/memento/presentation/component/MementoTimePicker.kt
app/src/main/java/org/memento/presentation/component/MementoTodoCheckBox.kt
app/src/main/java/org/memento/presentation/todo/TodoScreen.kt
app/src/main/java/org/memento/presentation/type/ColorTagData.kt
app/src/main/java/org/memento/presentation/type/DeadLineType.kt
app/src/main/java/org/memento/presentation/type/RepeatType.kt
app/src/main/java/org/memento/presentation/type/SelectorType.kt

- closed #22 
- 폴더링 구조 조금 바꿨어용
-## 📷 𝗦𝗰𝗿𝗲𝗲𝗻𝘀𝗵𝗼𝘁

[Hotfix/#22] 폴더링 구조 변경

---

app/src/main/java/org/memento/presentation/component/MementoAlertDialog.kt
app/src/main/res/values/strings.xml

- closed #41 
- alert dialog component 만들었습니다.
https://github.com/user-attachments/assets/2fa675a0-4909-4d20-8f01-03ef319096f9
아래 사용 예시도 확인해 주세요!
머지할 때 지울게요
🐑

[Feat/#41] alert dialog component

---

app/build.gradle.kts
app/src/main/java/org/memento/presentation/component/MementoScheduleItem.kt
app/src/main/java/org/memento/presentation/component/MementoTodoItem.kt
app/src/main/java/org/memento/presentation/navigator/component/BottomNavigationBar.kt
app/src/main/java/org/memento/presentation/navigator/component/BottomNavigationType.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/BrainDumpScreen.kt
app/src/main/java/org/memento/presentation/today/TodayScreen.kt
app/src/main/java/org/memento/presentation/util/LineThrough.kt
app/src/main/res/drawable/ic_add.xml
app/src/main/res/drawable/ic_today.xml
app/src/main/res/drawable/ic_todo.xml

- closed #42 
https://github.com/user-attachments/assets/ae80b3b2-76f0-4d2f-82bf-ee4cd0b555ca

[Feat/#42] Refactor UI

---

app/src/main/java/org/memento/domain/entity/AddTodo.kt
app/src/main/java/org/memento/presentation/component/MementoTimePicker.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/AddPlanScreen.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/AddPlanViewModel.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoScreen.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/BrainDumpScreen.kt

- closed #49 
- Add Plan 뷰 전송 버튼 추가
- BrainDump placeHolder 추가
- BrainDump scroll 오류 수정
- Calendar Dialog 기기 대응
- Calendar 로직 수정
https://github.com/user-attachments/assets/8be49b70-e351-447c-a916-a7c27f462485
디테일한 부분이 찾을 수록 많이 보이네요.. 수정 했습니다~
시간 역전 로직은, start time 기준으로 +2시간으로 변경되게 구현하였습니다!

[Fix/#49] bottom sheet fix detail

---

app/src/main/java/org/memento/data/datasource/AddPlanDataSource.kt
app/src/main/java/org/memento/data/datasourceimpl/AddPlanDataSourceImpl.kt
app/src/main/java/org/memento/data/dto/request/RequestAddTodoDto.kt
app/src/main/java/org/memento/data/mapper/toData/RequestAddTodoMapper.kt
app/src/main/java/org/memento/data/repositoryimpl/AddPlanRepositoryImpl.kt
app/src/main/java/org/memento/data/service/AddPlanService.kt
app/src/main/java/org/memento/domain/entity/AddTodo.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/AddScheduleScreen.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/AddScheduleViewModel.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoScreen.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoViewModel.kt
app/src/main/java/org/memento/presentation/util/FormatDate.kt

- closed #54 
- add todo api 구현
https://github.com/user-attachments/assets/6a97141d-bcbb-4a4d-a4d0-87069bdc58aa
반환 받을 때 toast 이슈가 좀 있네요.. 수정하겠습니다.

[Feat/#54] add todo api

---

app/src/main/java/org/memento/presentation/plusbottomsheet/BrainDumpAITextField.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/BrainDumpScreen.kt

- closed #64 
- 애니메이션 구현 완료
https://github.com/user-attachments/assets/c64aa84e-9497-4a3b-878b-dfe0d949dcce
현재는 isShowAnimation Boolean 타입으로 전달하고 있습니다. 추후에 UiState Loading에서 해당 boolean을 변경하는 방법으로 구현해야 할 것 같습니다.

[Feat/#64] brain dump feat animation

---

app/src/main/java/org/memento/presentation/main/MainScreen.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/AddScheduleScreen.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/AddScheduleViewModel.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoScreen.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoViewModel.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/BrainDumpScreen.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/BrainDumpViewModel.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/MainPlusBottomSheet.kt

- closed #66 
- 데이터 성공 시 BottomSheet 종료
- BottomSheet 종료 시 데이터 초기화
https://github.com/user-attachments/assets/8352d70b-7d55-4f7d-8459-feb99389117e
BottomSheet 종료 구현했습니다! 데이터 초기화도 완료요~

[Feat/#66] add plan 성공 시 화면 닫힘 및 데이터 초기화

---

app/src/main/java/org/memento/data/datasource/TodoDataSource.kt
app/src/main/java/org/memento/data/datasourceimpl/TodoDataSourceImpl.kt
app/src/main/java/org/memento/data/dto/response/ResponseTodoDto.kt
app/src/main/java/org/memento/data/mapper/toDomain/ResponseTodoMapper.kt
app/src/main/java/org/memento/data/repositoryimpl/TodoRepositoryImpl.kt
app/src/main/java/org/memento/data/service/TodoService.kt
app/src/main/java/org/memento/di/DataSourceModule.kt
app/src/main/java/org/memento/di/RepositoryModule.kt
app/src/main/java/org/memento/di/ServiceModule.kt
app/src/main/java/org/memento/domain/entity/TodoList.kt
app/src/main/java/org/memento/domain/repository/TodoRepository.kt
app/src/main/java/org/memento/presentation/todo/TodoViewModel.kt

[Feat/#61] todo api

---

app/src/main/java/org/memento/data/datasource/AddPlanDataSource.kt
app/src/main/java/org/memento/data/datasourceimpl/AddPlanDataSourceImpl.kt
app/src/main/java/org/memento/data/dto/response/ResponseTagDto.kt
app/src/main/java/org/memento/data/mapper/toDomain/ResponseAddPlanMapper.kt
app/src/main/java/org/memento/data/repositoryimpl/AddPlanRepositoryImpl.kt
app/src/main/java/org/memento/data/service/AddPlanService.kt
app/src/main/java/org/memento/domain/entity/Tag.kt
app/src/main/java/org/memento/domain/repository/AddPlanRepository.kt
app/src/main/java/org/memento/presentation/component/MementoTagBottomSheetItem.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/AddScheduleScreen.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/AddScheduleViewModel.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoTagScreen.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoViewModel.kt

- closed #77 
- tag 조회 api 구현
https://github.com/user-attachments/assets/5cba9776-6134-49ca-9b73-d507ffe84790

[Feat/#77] tag api

---

app/src/main/java/org/memento/presentation/component/MementoBottomSheet.kt
app/src/main/java/org/memento/presentation/component/MementoTagBottomSheetItem.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/AddScheduleScreen.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/AddScheduleViewModel.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoTagScreen.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoViewModel.kt

- closed #91 
- schedule에서 전달
- todo 에서 전달
https://github.com/user-attachments/assets/7cbadbec-af59-41e1-8c94-51707705bc8c
로그는 나만 볼거긔

[Hotfix/#91] tag id pass

---

app/src/main/java/org/memento/data/datasource/TodoDataSource.kt
app/src/main/java/org/memento/data/datasourceimpl/TodoDataSourceImpl.kt
app/src/main/java/org/memento/data/dto/request/RequestAddScheduleDto.kt
app/src/main/java/org/memento/data/dto/request/RequestAddTodoDto.kt
app/src/main/java/org/memento/data/repositoryimpl/TodoRepositoryImpl.kt
app/src/main/java/org/memento/data/service/TodoService.kt
app/src/main/java/org/memento/domain/entity/AddSchedule.kt
app/src/main/java/org/memento/domain/entity/AddTodo.kt
app/src/main/java/org/memento/domain/repository/TodoRepository.kt
app/src/main/java/org/memento/presentation/component/MementoDialog.kt
app/src/main/java/org/memento/presentation/component/MementoEditScheduleBottomSheet.kt
app/src/main/java/org/memento/presentation/component/MementoEditTodoBottomSheet.kt
app/src/main/java/org/memento/presentation/component/MementoScheduleItem.kt
app/src/main/java/org/memento/presentation/component/MementoTodoItem.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/AddScheduleScreen.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/AddScheduleViewModel.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoScreen.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoTagScreen.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoViewModel.kt
app/src/main/java/org/memento/presentation/today/TodayScreen.kt
app/src/main/java/org/memento/presentation/today/TodayViewModel.kt
app/src/main/java/org/memento/presentation/todo/TodoScreen.kt
app/src/main/java/org/memento/presentation/todo/TodoViewModel.kt
app/src/main/java/org/memento/presentation/util/FormatDate.kt

- closed #88 
- todo delete 구현
- today screen recomposition 구현
todo 삭제와 today screen recomposition 구현했습니다.

[Feat/#88] todo feat edit delete

---

app/src/main/java/org/memento/data/datasourceimpl/TodoDataSourceImpl.kt
app/src/main/java/org/memento/data/service/TodoService.kt
app/src/main/java/org/memento/presentation/todo/TodoViewModel.kt

- closed #97 
- todo screen api 수정
- ktlint check

[Hotfix/#97] toDo screen api fix

---

app/src/main/java/org/memento/data/datasource/ScheduleDataSource.kt
app/src/main/java/org/memento/data/datasourceimpl/ScheduleDataSourceImpl.kt
app/src/main/java/org/memento/data/repositoryimpl/ScheduleRepositoryImpl.kt
app/src/main/java/org/memento/data/service/ScheduleService.kt
app/src/main/java/org/memento/data/service/TodoService.kt
app/src/main/java/org/memento/domain/repository/ScheduleRepository.kt
app/src/main/java/org/memento/presentation/component/MementoScheduleItem.kt
app/src/main/java/org/memento/presentation/onboarding/viewmodel/OnboardingViewModel.kt
app/src/main/java/org/memento/presentation/today/TodayScreen.kt
app/src/main/java/org/memento/presentation/today/TodayViewModel.kt

- closed #90 
- 서버 데이터 변경에 따른 로직 수정
- UI 리컴포지션 수정

[Fix/90] todo today 로직 수정

---

app/src/main/java/org/memento/presentation/component/MementoEditScheduleBottomSheet.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/AddScheduleScreen.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/AddScheduleViewModel.kt
app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoViewModel.kt
app/src/main/java/org/memento/presentation/util/FormatDate.kt

- closed #99 
- add schedule 튕김 수정
- todo 로직 오류 수정
고생했다 얘들아 방어먹으러 가자

[Hotfix/#99] add logic fix

---

app/src/main/java/org/memento/presentation/component/MementoAnimatedGlowBorder.kt
app/src/main/java/org/memento/presentation/todo/TodoScreen.kt

- closed #100 
- AI 로딩 시에 애니메이션
- ToDo 없는 날짜는 실패 Toast
- 서버 통신과 함께 ai 우선순위 정렬 됩니다
https://github.com/user-attachments/assets/821f9c82-caf8-4f56-8e85-90499fb17434
메둥이들아 진짜 너무너무 고마옹 고생많았져

[Feat/#100] ai loading animation

---

app/src/main/java/org/memento/data/dto/response/ResponseTodoDto.kt
app/src/main/java/org/memento/domain/entity/TodoList.kt
app/src/main/java/org/memento/presentation/component/MementoTodoItem.kt
app/src/main/java/org/memento/presentation/today/TodayScreen.kt
app/src/main/java/org/memento/presentation/today/TodayViewModel.kt
app/src/main/java/org/memento/presentation/todo/TodoScreen.kt

- closed #101 
- ellipse 설정
- ai 버튼

[Hotfix/#101] error fix

---

.github/workflows/memento_ci.yml

- closed #
- ci yml 파일 actions/cache@v2 -> v4
이제 ci 잘 될 방구

[mod] Update memento_ci.yml

---

app/src/main/java/org/memento/data/dto/response/ResponsePriorityTodoDto.kt
app/src/main/java/org/memento/data/dto/response/ResponseScheduleDto.kt
app/src/main/java/org/memento/data/dto/response/ResponseTodoDto.kt
app/src/main/java/org/memento/domain/entity/ScheduleList.kt
app/src/main/java/org/memento/domain/entity/TodoList.kt
app/src/main/java/org/memento/presentation/today/TodayScreen.kt

- closed #114 
- dto 필드 바뀌어서 로딩안되던거 고쳤습니당
-
별거아니야

[hotfix/#114] orderNum 타입 변경

---

app/src/main/java/org/memento/data/service/AddPlanService.kt
app/src/main/java/org/memento/data/service/LoginService.kt
app/src/main/java/org/memento/data/service/ScheduleService.kt
app/src/main/java/org/memento/data/service/TodoService.kt
app/src/main/java/org/memento/data/service/UserInfoUpdateService.kt
app/src/main/java/org/memento/data/util/Interceptor.kt

- closed #118 
- 갱신 URL 엔드포인트 수정
- Service Endpoint 전면 수정
https://github.com/user-attachments/assets/2373e06f-0491-44c5-a34e-d8420994e042
테스트 완료
ㅠㅠㅠ 메멘토 개발자 분들 고맙읍니다.. 해결책을 주셔서 ...

[Hotfix/#118] 갱신 URL 수정

---

app/src/main/java/org/memento/data/datasource/SettingDataSource.kt
app/src/main/java/org/memento/data/datasourceimpl/SettingDataSourceImpl.kt
app/src/main/java/org/memento/data/repositoryimpl/SettingRepositoryImpl.kt
app/src/main/java/org/memento/data/service/SettingService.kt
app/src/main/java/org/memento/di/DataSourceModule.kt
app/src/main/java/org/memento/di/RepositoryModule.kt
app/src/main/java/org/memento/di/ServiceModule.kt
app/src/main/java/org/memento/domain/repository/SettingRepository.kt
app/src/main/java/org/memento/presentation/setting/SettingScreen.kt
app/src/main/java/org/memento/presentation/setting/SettingViewModel.kt

- closed #137 
- 충돌을 최소화 하기 위한 기초틀만 잡아놨어예
-
별거아니야

[Hotfix/#137] setting
